name: Java CI with Maven

on:
  push:
    branches: [ main, minju, jinwon, seonghun, seeum, jikwang ]
  pull_request:
    branches: [ main, minju, jinwon, seonghun, seeum, jikwang ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # client 프로젝트 (현재 레포)
      - name: Checkout ClassReservation (client)
        uses: actions/checkout@v3

      # 공통 모듈 (deu_sw_common)
      - name: Checkout ClassReservationCommon
        uses: actions/checkout@v3
        with:
          repository: chikchok1/deu_sw_common
          path: common

      # 서버 모듈 (deu_sw_server)
      - name: Checkout ClassReservationServer
        uses: actions/checkout@v3
        with:
          repository: chikchok1/deu_sw_server
          path: server

      # JDK 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # ✅ 공통 모듈 먼저 install
      - name: Install Common Module
        working-directory: ./common
        run: mvn clean install

      # ✅ 서버 모듈도 install
      - name: Install Server Module
        working-directory: ./server
        run: mvn clean install

      # ✅ 이제 client 빌드
      - name: Build and Test Client Module
        working-directory: ./ClassReservation
        run: mvn -B test
